version: '3.8'

services:
  js-playwright-ui-test:
    image: js-playwright-ui-test
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: npm run regression-chromium
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results